"""Writes config/wiki_plan.json. The plan is the curated, human-reviewed structure of the wiki:
readable note titles, topic folders, which source sections feed each note, and which related
notes to link (with the reason). Gemma drafts the note text from those sections."""
import json
B = "https://haas-ai-classes-fall-26.vercel.app/"
S = lambda i: f"raw/course-slides/haas-class{i}.html"
A_NET, A_PAC, A_LLM = ("raw/assignments/networking-tracker-README.md", "raw/assignments/pacman-dqn-README.md",
                       "raw/assignments/custom-llm-README.md")
titles = {1: "Class 1 slides (Code & Programming Foundations)", 2: "Class 2 slides (Software Systems)",
          3: "Class 3 slides (Machine Learning Foundations)", 4: "Class 4 slides (Deep Learning, Embeddings & Transformers)",
          5: "Class 5 slides (LLM Behavior, Prompting & Retrieval)"}
sources = [
  {"id": "networking-tracker-readme", "path": A_NET, "label": "Networking Tracker README", "public": True,
   "original_filename": "README.md", "origin": "my repo github.com/jdnathanson33/berkeley-networking-tracker"},
  {"id": "pacman-dqn-readme", "path": A_PAC, "label": "Pac-Man DQN README", "public": True,
   "original_filename": "README.md", "origin": "my repo github.com/jdnathanson33/pacman-dqn-assignment2"},
  {"id": "custom-llm-readme", "path": A_LLM, "label": "nanoGPT README", "public": True,
   "original_filename": "custom-llm-assignment4/README.md", "origin": "my repo github.com/jdnathanson33/custom-llm-assignment4"},
] + [{"id": f"class{i}-slides", "path": S(i), "label": titles[i], "public": False, "url": f"{B}class{i}.html",
      "original_filename": f"class{i}.html", "origin": f"course site {B}class{i}.html (instructor's slides; local copy only)"}
     for i in range(1, 6)]

def n(title, folder, focus, srcs, related):
    return {"title": title, "folder": folder, "focus": focus,
            "sources": [{"path": p, "sections": s} for p, s in srcs],
            "related": [{"title": t, "why": w} for t, w in related]}

H = "Fundamentals of Agentic AI"
notes = [
 # ---------------- Course
 n(H, "Course", "What the course covers class by class and how the assignments fit. Name each class and its main topics.",
   [(S(1), ["^slide 1:", "agenda"]), (S(2), ["^slide 1:", "agenda"]), (S(3), ["^slide 1:", "route"]),
    (S(4), ["^slide 1:", "roadmap"]), (S(5), ["^slide 1:", "what this class gives you"])],
   [("Class 1 - Code Foundations", "first class: code, terminal, Git, localhost, AI coding agents"),
    ("Class 2 - Software Systems", "second class: frontend, backend, databases, auth, deployment"),
    ("Class 3 - Machine Learning", "third class: training, evaluation, reinforcement learning"),
    ("Class 4 - Deep Learning and Transformers", "fourth class: neural networks, embeddings, attention"),
    ("Class 5 - LLMs Prompting and Retrieval", "fifth class: prompting, context, hallucination, RAG"),
    ("Networking Tracker", "project built after Class 2"), ("Pac-Man DQN Agent", "project built after Class 3"),
    ("Tiny nanoGPT Model", "project built after Class 4"), ("Personal Wiki Project", "this wiki, the Class 5 project")]),
 n("Class 1 - Code Foundations", "Course", "The goals, main topics, key takeaways, and the Discount Engine exercise of Class 1.",
   [(S(1), ["what success looks like", "agenda", "key takeaway", "the goal of this class", "definition of done", "the brief"])],
   [(H, "course map"), ("Git and GitHub", "version control taught in this class"), ("Localhost and Ports", "running software locally, taught in this class"),
    ("Clean Code", "code organization taught in this class"), ("AI Coding Agents", "Claude Code and Codex, introduced in this class"),
    ("Class 2 - Software Systems", "next class")]),
 n("Class 2 - Software Systems", "Course", "How a program becomes a product: the product stack, frontend, backend, databases, authentication, cloud deployment, and the assignment.",
   [(S(2), ["from a program to a product", "the product stack", "agenda", "what is a tech stack", "the assignment", "definition of done"])],
   [(H, "course map"), ("APIs and HTTP", "backend concept from this class"), ("Databases and SQL", "data layer from this class"),
    ("Authentication and Sessions", "auth from this class"), ("Cloud Deployment", "deployment from this class"),
    ("Networking Tracker", "the assignment for this class"), ("Class 1 - Code Foundations", "previous class"),
    ("Class 3 - Machine Learning", "next class")]),
 n("Class 3 - Machine Learning", "Course", "Why machine learning, how a model is trained, generalization, evaluation, unsupervised and reinforcement learning, and the Pac-Man project.",
   [(S(3), ["why ai instead of code", "last class we wrote the rules", "route", "three ways a machine can learn", "train an agent to play", "show what the agent actually learned"])],
   [(H, "course map"), ("Model Training and Gradient Descent", "core training idea from this class"),
    ("Overfitting and Generalization", "model choice from this class"), ("Precision and Recall", "evaluation from this class"),
    ("Reinforcement Learning", "RL from this class"), ("Pac-Man DQN Agent", "the assignment for this class"),
    ("Class 2 - Software Systems", "previous class"), ("Class 4 - Deep Learning and Transformers", "next class")]),
 n("Class 4 - Deep Learning and Transformers", "Course", "From hand-designed features to learned representations: neural networks, embeddings, attention, transformers, and the tiny LLM assignment.",
   [(S(4), ["from hand-designed features", "the limitation of classic ml", "roadmap", "a fluent answer is still a prediction", "assignment 3", "run it, then inspect"])],
   [(H, "course map"), ("Neural Networks", "covered in this class"), ("Tokens and Embeddings", "covered in this class"),
    ("Transformer Attention", "covered in this class"), ("Tiny nanoGPT Model", "the assignment for this class"),
    ("Class 3 - Machine Learning", "previous class"), ("Class 5 - LLMs Prompting and Retrieval", "next class")]),
 n("Class 5 - LLMs Prompting and Retrieval", "Course", "LLM behavior, fine-tuning vs prompting, context windows, thinking models, hallucination, RAG, and the personal wiki assignment.",
   [(S(5), ["what this class gives you", "=slide 6: agenda", "three levers, three jobs", "the golden rule", "four defenses", "retrieval augmented generation (rag)", "build your personal wiki"])],
   [(H, "course map"), ("Prompt Engineering", "covered in this class"), ("Context Windows", "covered in this class"),
    ("Fine-Tuning and LoRA", "covered in this class"), ("Hallucination", "covered in this class"),
    ("Retrieval Augmented Generation", "covered in this class"), ("Local Open Models", "covered in this class"),
    ("Personal Wiki Project", "the assignment for this class"), ("Class 4 - Deep Learning and Transformers", "previous class")]),
 # ---------------- Projects
 n("Networking Tracker", "Projects", "What I built (a private contact tracker), the stack I used and why, how it was tested and deployed, and its known limitations.",
   [(A_NET, ["#intro", "features", "technology stack", "what the tests verify", "known limitations"]), (S(2), ["the assignment"])],
   [(H, "course map"), ("Row Level Security", "how the app isolates each user's rows"), ("Authentication and Sessions", "how sign-in reaches the database"),
    ("Secrets and Environment Variables", "which values stay server-only"), ("Testing and CI", "the 30 automated tests"),
    ("Cloud Deployment", "deployed on Vercel"), ("Class 2 - Software Systems", "the class this assignment came from")]),
 n("Pac-Man DQN Agent", "Projects", "My three settings, the before/after evaluation scores, the training budget, one limitation, and the next experiment.",
   [(A_PAC, ["#intro", "my three settings", "what i expected", "evaluation: all five games", "actual training budget", "one limitation", "next experiment"])],
   [(H, "course map"), ("Deep Q-Networks", "the algorithm the agent uses"), ("Reinforcement Learning", "the learning setting"),
    ("Training Loss Curves", "loss went up while play barely improved"), ("Evaluation Design", "five games were too few to separate learning from luck"),
    ("Class 3 - Machine Learning", "the class this assignment came from")]),
 n("Tiny nanoGPT Model", "Projects", "The two tiny word-level models I trained, my settings and predictions, the eval results, the chat interface, and the limitation.",
   [(A_LLM, ["#intro", "four-row comparison", "my choices and prediction", "the runs", "chat interface", "one limitation"])],
   [(H, "course map"), ("Tokens and Embeddings", "traced token ids and embedding vectors"), ("Transformer Attention", "the model's 2 transformer blocks"),
    ("Sampling Temperature", "temperature comparison in the notebook"), ("Training Loss Curves", "loss evidence for both runs"),
    ("Evaluation Design", "48 fixed eval cases, public development tests"), ("Class 4 - Deep Learning and Transformers", "the class this assignment came from")]),
 n("Personal Wiki Project", "Projects", "The Class 5 assignment: a personal wiki with a local model, retrieval, and chat/ask/search modes.",
   [(S(5), ["build your personal wiki", "open models & running locally"])],
   [(H, "course map"), ("Retrieval Augmented Generation", "ask mode is a RAG workflow"), ("Local Open Models", "runs Gemma locally"),
    ("Context Windows", "passages must fit the context window"), ("Hallucination", "citations and insufficient-evidence answers are the defense"),
    ("Class 5 - LLMs Prompting and Retrieval", "the class this assignment came from")]),
 # ---------------- Concepts: software
 n("Git and GitHub", "Concepts", "What Git, repositories, branches, commits, diffs and pull requests are, and the workflow.",
   [(S(1), ["part: git, github"])],
   [("Class 1 - Code Foundations", "taught here"), ("AI Coding Agents", "agents need the same review discipline"),
    ("Secrets and Environment Variables", "never commit secrets")]),
 n("Localhost and Ports", "Concepts", "What localhost and ports are, why a site is a process, and why localhost links only work on your machine.",
   [(S(1), ["part: localhost"]), (S(2), ["localhost is for testing"])],
   [("Class 1 - Code Foundations", "taught here"), ("Cloud Deployment", "how software leaves localhost"),
    ("Local Open Models", "the local model server also runs on localhost")]),
 n("Clean Code", "Concepts", "Readability, guard clauses, named constants, one function one job, comments, and splitting projects by responsibility.",
   [(S(1), ["part: clean code"])],
   [("Class 1 - Code Foundations", "taught here"), ("AI Coding Agents", "reviewing what an AI writes"), ("Testing and CI", "tests make refactoring safe")]),
 n("AI Coding Agents", "Concepts", "Claude Code and Codex in the terminal, YOLO mode, plan mode, when not to use an agent, and reviewing an agent's diff.",
   [(S(1), ["part: ai coding agents", "reviewing what an ai writes"]), (S(5), ["tip: use plan mode"])],
   [("Class 1 - Code Foundations", "introduced here"), ("Git and GitHub", "diffs and pull requests are how agent work is reviewed"),
    ("Clean Code", "what to look for in generated code"), ("Prompt Engineering", "clear prompts improve agent output")]),
 n("APIs and HTTP", "Concepts", "APIs as agreements, HTTP methods, JSON, status codes, and never trusting incoming requests.",
   [(S(2), ["apis: the waiter", "an api is an agreement", "http methods", "json", "never trust incoming", "status codes", "anatomy of an http request"]),
    (A_NET, ["request flow, in words"])],
   [("Class 2 - Software Systems", "taught here"), ("Networking Tracker", "its /api routes follow this pattern"),
    ("Authentication and Sessions", "requests carry the session"), ("Databases and SQL", "the backend talks to the database")]),
 n("Databases and SQL", "Concepts", "Why apps need databases, tables and relationships, SQL, database types, and my contacts table.",
   [(S(2), ["part: databases give apps memory"]), (A_NET, ["database schema", "public.contacts"])],
   [("Class 2 - Software Systems", "taught here"), ("Row Level Security", "Postgres enforces row ownership"),
    ("Networking Tracker", "uses Neon Postgres"), ("APIs and HTTP", "the API sits in front of the database")]),
 n("Authentication and Sessions", "Concepts", "Why authentication matters, how sign-in works, and how identity travels from the browser to Postgres in my app.",
   [(S(2), ["part: authentication"]), (A_NET, ["how identity gets from the browser"])],
   [("Class 2 - Software Systems", "taught here"), ("Row Level Security", "the database uses the verified identity to filter rows"),
    ("Secrets and Environment Variables", "the cookie secret must stay server-only"), ("Networking Tracker", "implemented with Neon Managed Better Auth")]),
 n("Row Level Security", "Concepts", "How Postgres RLS isolates each user's rows in my networking tracker: the four policies, USING vs WITH CHECK, grants, and the user_id default.",
   [(A_NET, ["the four policies", "why user_id"])],
   [("Networking Tracker", "where I applied it"), ("Authentication and Sessions", "RLS depends on a verified JWT"),
    ("Databases and SQL", "RLS is a Postgres feature")]),
 n("Secrets and Environment Variables", "Concepts", "Keeping secrets out of code: which environment variables are public or server-only and why.",
   [(S(2), ["keep secrets out of your code"]), (A_NET, ["environment variables"])],
   [("Networking Tracker", "its five environment variables"), ("Git and GitHub", "never commit secrets"),
    ("Cloud Deployment", "secrets are set per environment in Vercel")]),
 n("Testing and CI", "Concepts", "Tests as executable promises, CI/CD as a release gate, regression tests, the test pyramid, and my 30 tests.",
   [(S(1), ["tests turn examples"]), (S(2), ["ci/cd uses tests", "regression tests", "the test pyramid"]), (A_NET, ["what the tests verify"])],
   [("Networking Tracker", "25 validation + 5 route-contract tests"), ("Cloud Deployment", "tests gate releases"), ("Clean Code", "tests make changes safe")]),
 n("Cloud Deployment", "Concepts", "What the cloud is, deploying an app, environments, rollback, and how I deployed on Vercel.",
   [(S(2), ["part: cloud platforms", "environments are intentionally", "rollback"]), (A_NET, ["> deployment"])],
   [("Class 2 - Software Systems", "taught here"), ("Networking Tracker", "deployed on Vercel"),
    ("Testing and CI", "tests as a release gate"), ("Localhost and Ports", "local vs deployed")]),
 # ---------------- Concepts: ML
 n("Model Training and Gradient Descent", "Concepts", "Parameters, loss, and gradient descent: how a model improves from a poor first guess.",
   [(S(3), ["part: training a model"])],
   [("Class 3 - Machine Learning", "taught here"), ("Neural Networks", "the same loop trains deep networks"),
    ("Training Loss Curves", "what loss looked like in my runs"), ("Overfitting and Generalization", "fitting is not the same as generalizing")]),
 n("Overfitting and Generalization", "Concepts", "Test sets, overfitting, bias and variance, baselines, and what my validation split did and did not show.",
   [(S(3), ["keep a test set outside", "separate fitting, choosing", "overfitting fits noise", "bias and variance", "compare against a simple baseline"]),
    (A_LLM, ["loss evidence"])],
   [("Class 3 - Machine Learning", "taught here"), ("Evaluation Design", "how I evaluated my own models"),
    ("Training Loss Curves", "train vs validation loss"), ("Tiny nanoGPT Model", "validation used the same templates")]),
 n("Precision and Recall", "Concepts", "True/false positives, why accuracy can hide errors, precision vs recall, thresholds, and decision policies.",
   [(S(3), ["part: evaluating predictions"])],
   [("Class 3 - Machine Learning", "taught here"), ("Evaluation Design", "choosing what to measure"), ("Overfitting and Generalization", "evaluate on held-out data")]),
 n("Reinforcement Learning", "Concepts", "Agents, actions, rewards now vs later, Q-learning, exploration, and why a reward defines what is optimized.",
   [(S(3), ["part: reinforcement learning", "the q-learning update"])],
   [("Class 3 - Machine Learning", "taught here"), ("Deep Q-Networks", "Q-learning with a neural network"), ("Pac-Man DQN Agent", "my RL project")]),
 n("Deep Q-Networks", "Concepts", "How a DQN plays Atari: frames, actions, clipped rewards, replay memory, target network, and the limits I saw.",
   [(S(3), ["why dqn uses replay", "a q-table cannot list"]), (A_PAC, ["how the agent works", "one limitation"])],
   [("Reinforcement Learning", "the broader setting"), ("Pac-Man DQN Agent", "my DQN run"), ("Neural Networks", "the Q-function is a neural network")]),
 n("Neural Networks", "Concepts", "Neurons, nonlinearity, the training loop, parameters vs hyperparameters, optimizers, batches, and epochs.",
   [(S(4), ["part: neural networks", "the training loop", "parameters vs hyperparameters", "optimizers choose", "batches make", "epochs revisit"])],
   [("Class 4 - Deep Learning and Transformers", "taught here"), ("Model Training and Gradient Descent", "the same update idea"),
    ("Transformer Attention", "transformers are neural networks"), ("Deep Q-Networks", "a network estimates action values")]),
 n("Training Loss Curves", "Concepts", "What training and validation loss showed in my Pac-Man and nanoGPT runs, and why lower loss is not the same as better results.",
   [(A_PAC, ["what i expected"]), (A_LLM, ["loss evidence"])],
   [("Pac-Man DQN Agent", "loss rose as the agent improved a little"), ("Tiny nanoGPT Model", "loss fell 86% then flattened"),
    ("Model Training and Gradient Descent", "what loss measures"), ("Overfitting and Generalization", "train vs validation gap")]),
 n("Evaluation Design", "Concepts", "How I evaluated my models: fixed seeds and eval suites, small noisy samples, public development tests, and what I would change.",
   [(A_PAC, ["evaluation: all five games", "one limitation", "next experiment"]), (A_LLM, ["four-row comparison", "one limitation"])],
   [("Pac-Man DQN Agent", "five-game evaluation"), ("Tiny nanoGPT Model", "48-case eval suite"),
    ("Precision and Recall", "choosing the metric"), ("Overfitting and Generalization", "keep test data separate")]),
 # ---------------- Concepts: language models
 n("Tokens and Embeddings", "Concepts", "How words become tokens and IDs, and how embeddings place words as vectors; with the actual values from my nanoGPT run.",
   [(S(4), ["the problem: words", "words as points", "distance reflects", "context determines", "how words become tokens"]), (A_LLM, ["tracing the learning process"])],
   [("Tiny nanoGPT Model", "where I traced tokens and embeddings"), ("Transformer Attention", "attention updates token vectors"),
    ("Class 4 - Deep Learning and Transformers", "taught here"), ("Retrieval Augmented Generation", "embeddings power vector search")]),
 n("Transformer Attention", "Concepts", "Why attention replaced RNNs, how attention combines context, the transformer block, and generating one token at a time.",
   [(S(4), ["part: sequences & attention", "the transformer block", "generating text, one token"])],
   [("Class 4 - Deep Learning and Transformers", "taught here"), ("Tokens and Embeddings", "attention works on token vectors"),
    ("Tiny nanoGPT Model", "2 transformer blocks, 4 heads"), ("Context Windows", "attention cost grows with context")]),
 n("Sampling Temperature", "Concepts", "What temperature does to next-token probabilities, and what I saw at 0.3, 0.8 and 1.2.",
   [(S(5), ["temperature: the creativity dial", "llms are probabilistic"]), (A_LLM, ["tracing the learning process"])],
   [("Tiny nanoGPT Model", "temperature comparison"), ("Prompt Engineering", "prompts and temperature both steer the distribution"),
    ("Hallucination", "sampling can produce fluent wrong text")]),
 n("Prompt Engineering", "Concepts", "Prompting as probability steering, context, clear asks, system prompts, and project instruction files.",
   [(S(5), ["part: prompting", "part: prompt engineering"])],
   [("Class 5 - LLMs Prompting and Retrieval", "taught here"), ("Context Windows", "the prompt is part of the context"),
    ("Fine-Tuning and LoRA", "the other levers besides prompting"), ("Personal Wiki Project", "persona and research rules are system prompts")]),
 n("Context Windows", "Concepts", "What a context window is, how big it is, context rot, compression, and putting stable rules in stable places.",
   [(S(5), ["part: context windows and memory"])],
   [("Class 5 - LLMs Prompting and Retrieval", "taught here"), ("Prompt Engineering", "what goes into the context"),
    ("Retrieval Augmented Generation", "select relevant passages instead of sending everything")]),
 n("Fine-Tuning and LoRA", "Concepts", "Fine-tuning and RLHF, their cost, and when to use prompting vs LoRA vs fine-tuning.",
   [(S(5), ["part: what is fine-tuning?"])],
   [("Class 5 - LLMs Prompting and Retrieval", "taught here"), ("Prompt Engineering", "the cheaper lever"),
    ("Retrieval Augmented Generation", "RAG adds knowledge without retraining")]),
 n("Hallucination", "Concepts", "Why fluent systems can be wrong and the four defenses against it.",
   [(S(5), ["part: hallucination is a system property", "it knows"]), (S(4), ["a fluent answer is still a prediction"])],
   [("Class 5 - LLMs Prompting and Retrieval", "taught here"), ("Retrieval Augmented Generation", "grounding answers in sources"),
    ("Sampling Temperature", "sampling adds variety and risk")]),
 n("Retrieval Augmented Generation", "Concepts", "What RAG is, why it matters, how it works (chunking, embeddings, vector search), and its limits.",
   [(S(5), ["part: retrieval augmented generation"])],
   [("Class 5 - LLMs Prompting and Retrieval", "taught here"), ("Personal Wiki Project", "my RAG implementation"),
    ("Tokens and Embeddings", "embeddings make vector search possible"), ("Hallucination", "RAG is one defense"),
    ("Context Windows", "retrieved passages must fit the context")]),
 n("Local Open Models", "Concepts", "Open-weight models, model tiers, running models locally, and thinking models.",
   [(S(5), ["open models & running locally", "model tiers", "what are “thinking” models", "the biggest shift since gpt"])],
   [("Class 5 - LLMs Prompting and Retrieval", "taught here"), ("Personal Wiki Project", "runs Gemma locally"),
    ("Localhost and Ports", "the model server listens on localhost")]),
]
json.dump({"_comment": "Curated wiki structure. Edit titles/sections/links here; `wiki ingest` drafts note text with Gemma.",
           "sources": sources, "notes": notes}, open("config/wiki_plan.json", "w"), indent=1, ensure_ascii=False)
print(len(notes), "notes")
