#!/usr/bin/env python3
"""Launcher: ./wiki <command>. See ./wiki --help."""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from wiki_harness.cli import main  # noqa: E402

sys.exit(main())
